### PR TITLE
Refactor main mecanism (a.k.a v2)

### PR DESCRIPTION
**Pull request by Taluu**
Ref #35, #16 and #5  
- [x] Create the snapshot interfaces
- [x] implement the recursive
- [x] Refactor how the object snapshots are built
- [x] Refactor how the array snapshots are built
- [x] Refactor how the collection snapshot is built
- [x] Reflect changes on the Set
- [ ] Implement "comparator"
- [ ] Tests

### CODE REVIEW

**Comment by peter279k** [comment]
The Travis CI build is failed because of the wrong `PHPUnit` namespace.

Using the `PHPUnit\Framework\TestCase` instead.

BTW, the commits are very large and it should squash all commits to one commit if possible.

**Comment by Taluu** [comment]
Hum, guess this is expected, as the last build dates from (almost) 2 years ago, as I didn't continue (even if it's on my todo list, but as I'm not currently using this lib...).

And I'm against squashing commits, and prefer to stay true to the atomic commits rule (makes it easier with bisects when looking out for bugs, have a proper history, ... and so on). :}

**Comment by peter279k** [comment]
Ok. It makes sense :).

**Comment by Taluu** [comment]
As it's been a while, I don't think continuing on this path is relevant anymore.

If I ever need to maintain this lib, I think I will do so differently than proposed right here.

Let's cleanup (But keep a branch for ref)

**Pull request closed without merging**
